### ISSUE TITLE
AssemblyListCount label appends count each time List Assemblies is clicked

### ISSUE THREAD

**Issue by Compupaq** [gashupl/gacexplorer#14]
When you click on List Assemblies, instead of overwriting the count at the bottom, it appends it.

![image](https://user-images.githubusercontent.com/48487839/109553440-0a88e880-7aa1-11eb-8a50-41931fd3aebb.png)

**Comment by gashupl** [comment]
Issue confirmed. Working on fix.

**Comment by Compupaq** [comment]
I have a proposed fix for it.  Modify this line:

https://github.com/gashupl/gacexplorer/blob/ce616e424c5484747284c9d3f86527ea90d3350a/App/GacExplorer.UI/Commands/ListAssembliesCommand.cs#L58

To look like this line:
`this.lblAssemblyListCount.Text = "Number of Assemblies: " + Program.AssemblyLineList.Count.ToString();`

**Comment by gashupl** [comment]
Code updated. New build available on: http://piotrgaszewski.pl/release/gacexplorer/GacExplorer-1.1.1.0.zip
