### ISSUE TITLE
Unable to register an assembly if the file path includes a space

### ISSUE THREAD

**Issue by Compupaq** [gashupl/gacexplorer#15]
The following error comes up
![image](https://user-images.githubusercontent.com/48487839/109555068-17a6d700-7aa3-11eb-9c68-ae7206dac780.png)

The portion after 'Unknown Option:' in the screenshot is the file path after a space (eg.  if the file path is C:\Path\To A\File.dll, the error is Unknown Option:  A\File.dll).

**Comment by gashupl** [comment]
Issue confirmed. Working on fix.

**Comment by Compupaq** [comment]
I was able to get it working by modifying this line:

https://github.com/gashupl/gacexplorer/blob/ce616e424c5484747284c9d3f86527ea90d3350a/App/GacExplorer.CommandProxy/Gacutil.cs#L35

To these two lines:

```
string arguments = "/i \"" + path + "\"";
output = StartProcess(gacutilProcess, arguments, true);
```

I remembered shortly after posting the issues that I could just download the source and see if I could figure it out.

**Comment by gashupl** [comment]
Code updated. New build available on: http://piotrgaszewski.pl/release/gacexplorer/GacExplorer-1.1.1.0.zip
